---
date: "2016-04-27T00:00:00Z"
external_link: ""

#slides: example
title: Videos tutorials
summary: All videos tutorial
toc: true
output:
  blogdown::html_page:
    toc: true
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""

---
In this section, you'll find tutorial videos for the various courses taught at the University of Gabes. 

# 1) My videos

## calcul du taux de rendement du vendeur d'un call
<iframe width="560" height="315" src="https://www.youtube.com/embed/nEgyLsHnJyY?si=pYifymiJKAqpNxBY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  calcul du taux de rendement de l'acheteur d'un call

<iframe width="560" height="315" src="https://www.youtube.com/embed/N4sdCB7d6LI?si=PgF2uoY8f78pV_d0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Définition de la VaR
<iframe width="560" height="315" src="https://www.youtube.com/embed/D7-Bqx4o5ic?si=7Z4WyZxbGA6qQuy3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Gain de l'acheteur d'un Call

<iframe width="560" height="315" src="https://www.youtube.com/embed/-iUKH_Uqmuk?si=BC2D4R2wqyRH_16J" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Option Call: notion de profit

<iframe width="560" height="315" src="https://www.youtube.com/embed/YFi44o9Vaew?si=x1Sbj2X7FkJwTq4P" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Définition de l'option:  partie 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/BPgh5QyITcE?si=DixBGCrHZLZS7Vuy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Définition de l'option: partie 2
<iframe width="560" height="315" src="https://www.youtube.com/embed/Gid9GK0i4e4?si=B5g5QFnEnAeSEzr2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Gordon Shapiro

<iframe width="560" height="315" src="https://www.youtube.com/embed/3iOdeKkvuIM?si=71REu-hDXDPQS-dR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Le TRI
<iframe width="560" height="315" src="https://www.youtube.com/embed/R-wuFFN78iU?si=j36SKJrSF-isQM2N" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Evaluation de taux d'actualisation avec la méthode de fisher

<iframe width="560" height="315" src="https://www.youtube.com/embed/658suO_fjfc?si=wXqnpCejd2sbrcUi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Simulation historique a M titres de la VaR

<iframe width="560" height="315" src="https://www.youtube.com/embed/PZAVpb3mPxw?si=nN9wrZFx0NeFoytP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Simulation historique VaR 

<iframe width="560" height="315" src="https://www.youtube.com/embed/5RcxvbmExwE?si=IHnpwAhptVmvzUu0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Evaluation de la valeur finale dans ma méthode de Fisher

<iframe width="560" height="315" src="https://www.youtube.com/embed/b-ja4RyU98A?si=F0ZuquMInnPIkx4y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Evaluation par la méthode de Fisher

<iframe width="560" height="315" src="https://www.youtube.com/embed/1WVJGg1QGTs?si=VGkcb4PDq7cgHEe3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Valeur Actuelle Nette (VAN) présentation 2/2

<iframe width="560" height="315" src="https://www.youtube.com/embed/b9SyJ67ThQA?si=Ymppm-deSad94vD0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

##  Valeur Actuelle Nette (VAN) présentation 1/2


<iframe width="560" height="315" src="https://www.youtube.com/embed/m7aBNRLOQGE?si=eVckcwWEh01bgJu4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>



















# 2)  Other videos

## The Garch model

<iframe width="560" height="315" src="https://www.youtube.com/embed/anCMsvUbKlM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## V-Lab (volatility)

<iframe width="560" height="315" src="https://www.youtube.com/embed/kZaqBJQvar0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Research in finance

<iframe width="560" height="315" src="https://www.youtube.com/embed/fio14ZJVucg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


## What is Entropy ? 

<iframe width="560" height="315" src="https://www.youtube.com/embed/YtebGVx-Fxw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Gradient descent 
<iframe width="560" height="315" src="https://www.youtube.com/embed/sDv4f4s2SB8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Neural Network 

<iframe width="560" height="315" src="https://www.youtube.com/embed/CqOfi41LfDw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Time series (introduction)

<iframe width="560" height="315" src="https://www.youtube.com/embed/9a70xIMLuzw?si=9U6w2qgnSWAJIbTH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Time series (concepts)
<iframe width="560" height="315" src="https://www.youtube.com/embed/CcTCILi6Azc?si=y1d6y0o8O7M7TMUZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


## model construction
<iframe width="560" height="315" src="https://www.youtube.com/embed/Cc4EeYIVZ44?si=VU2wkE7E4vjYP3_-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


